# Generated by Django 2.2.6 on 2019-11-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
