# Generated by Django 2.2.6 on 2019-11-10 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
