# Generated by Django 2.2.6 on 2019-11-11 00:28

from django.db import migrations, models
import oxcimarron.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191110_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[oxcimarron.utils.validate_file_size]),
        ),
    ]
