# Generated by Django 2.2.6 on 2019-11-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20191109_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='imageTest',
        ),
    ]
