# Generated by Django 2.2.6 on 2019-11-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20191109_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='t2',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
