# Generated by Django 2.2.6 on 2019-11-12 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20191110_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='imageTest',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='t2',
        ),
    ]
