# Generated by Django 2.2.6 on 2019-10-17 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=60)),
                ('first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('country_of_origin', models.CharField(max_length=30)),
                ('birth_year', models.CharField(blank=True, max_length=5, null=True)),
                ('death_year', models.CharField(blank=True, max_length=5, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PageFix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.CharField(default='', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('year_written', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=30, null=True)),
                ('standard_pages', models.IntegerField(blank=True, null=True)),
                ('year_read', models.IntegerField(blank=True, null=True)),
                ('enjoyment', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reading.Author')),
            ],
            options={
                'ordering': ['title', 'year_read'],
            },
        ),
    ]
