# Generated by Django 2.2.6 on 2019-11-01 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_auto_20191031_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['year_read', 'title']},
        ),
    ]
