# Generated by Django 2.0.2 on 2019-01-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('personal_rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
            options={
                'ordering': ['name', 'location'],
            },
        ),
        migrations.CreateModel(
            name='SkiDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('year_written', models.IntegerField(blank=True, null=True)),
                ('miles', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('top_speed', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('vertical_feet', models.IntegerField(blank=True, null=True)),
                ('resort', models.ManyToManyField(to='skiing.Resort')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
