# Generated by Django 2.0.2 on 2019-01-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skiing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resort',
            options={'ordering': ['resort_name', 'location']},
        ),
        migrations.RenameField(
            model_name='resort',
            old_name='name',
            new_name='resort_name',
        ),
    ]
