# Generated by Django 2.2.6 on 2019-10-14 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skiing', '0003_remove_skiday_year_written'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resort',
            options={'ordering': ['resort_name', 'location', 'personal_rating']},
        ),
    ]
