# Generated by Django 2.2.6 on 2019-10-14 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skiing', '0004_auto_20191014_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resort',
            options={'ordering': ['resort_name', 'location']},
        ),
    ]
