# Generated by Django 2.2.6 on 2019-10-17 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skiing', '0005_auto_20191014_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='acres',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resort',
            name='vertical_feet',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='skiday',
            name='resort',
        ),
        migrations.AddField(
            model_name='skiday',
            name='resort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skiing.Resort'),
        ),
    ]
