# Generated by Django 2.2.6 on 2019-10-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiing', '0006_auto_20191017_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skiday',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
