# Generated by Django 2.2.6 on 2019-10-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiing', '0008_auto_20191023_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='longest_run',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
