# Generated by Django 2.2.6 on 2019-10-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiing', '0009_auto_20191023_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='skiday',
            name='miles_alt',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='skiday',
            name='top_speed_alt',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='skiday',
            name='trip_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skiday',
            name='vertical_feet_alt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
