# Generated by Django 2.2.6 on 2019-10-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skiing', '0010_auto_20191027_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skiday',
            options={'ordering': ['skidate']},
        ),
        migrations.RenameField(
            model_name='skiday',
            old_name='date',
            new_name='skidate',
        ),
    ]
