# Generated by Django 2.2.6 on 2019-11-04 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skiing', '0011_auto_20191027_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skiday',
            name='resort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skidays', to='skiing.Resort'),
        ),
    ]
