# Generated by Django 2.2.6 on 2019-11-06 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skiing', '0012_auto_20191104_0729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skiday',
            options={'ordering': ['-skidate']},
        ),
    ]
