# Generated by Django 2.2.6 on 2019-11-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiing', '0013_auto_20191105_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='resort_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
