# Generated by Django 2.2.6 on 2019-11-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiing', '0014_auto_20191107_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='resort_name',
            field=models.CharField(max_length=60),
        ),
    ]
