# Generated by Django 2.2.6 on 2019-12-30 19:00

import datetime
from django.db import migrations, models
import skiing.models


class Migration(migrations.Migration):

    dependencies = [
        ('skiing', '0015_auto_20191107_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skiday',
            name='skidate',
            field=models.DateField(default=datetime.datetime(2019, 12, 30, 13, 0, 19, 217739), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='skiday',
            name='trip_no',
            field=models.IntegerField(blank=True, default=skiing.models.get_trip_no_default, null=True),
        ),
    ]
