# Generated by Django 2.2.6 on 2019-12-30 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skiing', '0016_auto_20191230_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skiday',
            name='skidate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
